name: BDD Cucumber Selenium TestNG CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: BDD Selenium Test
      run: mvn -B test 

    - name: Run tests with Maven
      run: |
        mvn clean
        mvn -B package
